name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set timestamp for tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: eu-north-1

    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag 80202038201.dkr.ecr.eu-north-1.amazonaws.com/custody-solution-api-dev:${{ env.IMAGE_TAG }}

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v2
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-north-1
        image: 80202038201.dkr.ecr.eu-north-1.amazonaws.com/custody-solution-api-dev:${{ env.IMAGE_TAG }}
        
    
